import { getPlan } from '@/lib/entitlements';

export type WatermarkContext = {
  planId: string | null;
  isTrialing?: boolean;
};

export function shouldDisplayWatermark({ planId, isTrialing = false }: WatermarkContext): boolean {
  if (!planId) {
    return true;
  }

  const plan = getPlan(planId);
  if (!plan) {
    return true;
  }

  if (plan.watermark) {
    return true;
  }

  return isTrialing;
}

export function watermarkCopy(): string {
  return 'Draft export · Generated by KatoSuite';
}
